# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('project', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('other', 'Other')], max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('existing', 'Existing')], max_length=200)),
                ('timeline', models.CharField(choices=[('now', 'Now'), ('week', 'One Week'), ('month', 'One Month'), ('months', 'Two Months')], max_length=200)),
            ],
        ),
    ]
