# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-19 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.FileField(blank=True, upload_to='images/%Y%m%d')),
                ('is_draft', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('project', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('strategy', 'Digital Strategy'), ('other', 'Other')], max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('existing', 'Existing')], max_length=200)),
                ('timeline', models.CharField(choices=[('now', 'Now'), ('week', 'One Week'), ('month', 'One Month'), ('months', 'Two Months')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image1', models.FileField(blank=True, upload_to='images/%Y%m%d')),
                ('image2', models.FileField(blank=True, upload_to='images/%Y%m%d')),
                ('image3', models.FileField(blank=True, upload_to='images/%Y%m%d')),
                ('image4', models.FileField(blank=True, upload_to='images/%Y%m%d')),
                ('excerpt', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
